### ISSUE TITLE
'UPDATE_RESOURCES' action is undefined in actionTypes

### ISSUE THREAD

**Issue by rquantz** [jamesplease/redux-resource#402]
The UPDATE_RESOURCES action is in the docs and is recognized correctly by the reducer, but is not included in actionTypes.

**Comment by jamesplease** [comment]
Good call...not sure how I missed this. I'll do a bug fix today. Thanks for raising the issue @rquantz !

**Comment by rquantz** [comment]
Excellent, thank you!

**Comment by jamesplease** [comment]
@rquantz , this has been released as `redux-resource@3.0.2`. Thanks again for noticing this and opening an issue. I appreciate it!

**Comment by rquantz** [comment]
Thanks for fixing so quickly!
