### ISSUE TITLE
Is there anyway to get Promise from `redux-resource-xhr`?

### ISSUE THREAD

**Issue by knightus** [jamesplease/redux-resource#409]
Hi @jamesplease ,

I've just found out `redux-resource` last weekend and it has a great documentation & covers many cases that I've concerned of.

But there's one thing that bugged me is `redux-resource-xhr`'s crudRequest returns `XMLHttpRequest` instead of `Promise`. Thus, it's hard to make it works in some cases:

- chain the dispatches: `dispatch(Actions.jobOpeningCreate({ data })).then(...)`
- combine with `redux-form`'s submitting, since it works with Promise-only

I've read included `xhr.js` file and seen that there's a check to return Promise if the callback is not a function. But `crudRequest` always pass a function callback to `xhr()`

I worked-around by promisify the returned `XMLHTTPRequest`, but it's quite tedious and redundant accross the action creators

So is there any convenient way to return `Promise` instead of `XMLHTTPRequest` when using `redux-resource-xhr`?

**Comment by jamesplease** [comment]
Hi @knightus ! Thanks for opening the issue. Unfortunately, there is not, and I can't think of a way to make that work while still having the API allow you to cancel requests easily.

I've been meaning to make `redux-resource-fetch`, but I haven't gotten around to it. If you'd prefer to work with Promises always, then it make sense to roll your own wrapper. `redux-resource-xhr` isn't too big!

Thanks! :v:

**Comment by knightus** [comment]
Thank @jamesplease for the really quick response! So that's a trade-off. In my use cases, I don't have to cancel the requests much.

But I can see the idea here. Will work on a wrapper instead 👌

**Comment by jamesplease** [comment]
Let me know if you run into any issues. And if you get around to making a wrapper that uses `fetch`, it could become the official `redux-resource-fetch` if you are interested!

**Comment by knightus** [comment]
Sure! I'm using `axios` but since the purpose is to make it return `Promise` in order to be compatible with other libs, I think it would be the same possibility with `fetch`. Will get back to you soon ;)

**Comment by jamesplease** [comment]
Cool, that makes sense. Well, if you end up making a `redux-resource-axios` library, then that could be added to the core libraries as well 🙂I'd love to provide more options for people!
