### ISSUE TITLE
Included resources for CREATE_RESOURCES_SUCCEEDED

### ISSUE THREAD

**Issue by GuillaumeJasmin** [jamesplease/redux-resource#414]
Hi,
First, thanks for the library. It's very powerful and easy to use even with big application. I first build a similar library but redux-resources is more advanced so I migrate here.
 
I have one question. Currently, included resources work only with read action

`src/included-resources.js` line 15 :
```js
// This plugin only works for successful reads at the moment
if (type !== actionTypes.READ_RESOURCES_SUCCEEDED) {
  return state;
}
```

My question is simple, why ? It could be useful for creation ?

**Comment by jamesplease** [comment]
Agreed. PRs welcome!

**Comment by jamesplease** [comment]
@GuillaumeJasmin , I'm going to spend one or two more days thinking about this. There may have been some edge case I was trying to avoid by supporting CREATE_RESOURCES. I apologize for the delay!

In the meantime, I released `redux-resource@3.0.4` with a fix for the bug that you reported over in #413 

Thank you _so much_ for your contributions these past few weeks!

**Comment by jamesplease** [comment]
I ended up having time tonight. This was just released as `redux-resource-plugins@3.1.0`. Let me know how that works for ya. Also, thanks again, @GuillaumeJasmin !

**Comment by GuillaumeJasmin** [comment]
Perfect ! I just update my version and it still working ! Thanks :)

**Comment by jamesplease** [comment]
Awesome! Glad to hear it!
