### ISSUE TITLE
OPTIONS Requests

### ISSUE THREAD

**Issue by djstein** [jamesplease/redux-resource#418]
Hey gang, I was recommended to pop in from Reddit after some discussion on about reusable Redux factories. Thank you for your work so far, looks great!

One thing I may have missed in the docs is the ability to fetch OPTIONS of an endpoint. I believe that this would be a crucial addition to the reducer and could be stored as a key in say:
```javascript
[resourceKey]: {
  resourceType: 'books',
  resources: {},
  meta: {},
  lists: {},
  options: {}, <-- new
  requests: {}
}
```
These options are extremely useful for knowing what can be done to a particular HTTP Resource.
The biggest need for OPTIONS requesting is form generation.
For example, obtaining the OPTIONS of resource `/books` and would return an object. One of the keys being POST. The instructions of POST, PUT, PATCH will tell us what we can actually send in a data packet to that resource. This is fantastic for allowing us to create new forms when the data we already have!

Some other use cases may be providing the URL structure or resources to programmatically fetch lists or objects.

Note: could this be achieved with ```import { crudRequest } from 'redux-resource-xhr';``` and passing  `method: 'OPTIONS'` ? The returned value simply would not have a dedicated key in the store.

If this has any traction I would more than likely help out!

**Comment by djstein** [comment]
@jamesplease thanks! I believe that a plugin would be great. For plugins, should those libraries be created in my own repository? If yes, I will simply write a rollup application for everyone to use.

**Comment by jamesplease** [comment]
> For plugins, should those libraries be created in my own repository?

Yup! 👍

I’ll close this out, but feel free to leave another comment if you run into problems. Id be happy to help!

**Comment by djstein** [comment]
for those people who stumble upon this, this is the current implementation of fetching OPTIONS (no error handling) that will place those options of an endpoint into the META for a resource. This example is using `redux-saga` but could quickly be switched out for `redux-thunk` by replacing `put` for `dispatch`.
```js
import { takeEvery, call, put, all, fork } from 'redux-saga/effects'
import { actionTypes } from 'redux-resource'

import { xhr } from 'redux-resource-xhr'

function* handleOptionsRequest(apiRoot, action) {
  const url = `${apiRoot}/${action.uri}/`
  const options = {
    method: 'OPTIONS',
    json: true,
  }
  const request = yield xhr(url, options)

  yield put({
    resourceType: action.resourceType,
    type: 'UPDATE_RESOURCES',
    meta: { [action.resourceType]: { options: request.body } },
  })
}

function* genericOptionsWatcher(apiRoot, action) {
  yield takeEvery('FETCH_OPTIONS', handleOptionsRequest, apiRoot)
}

export default function* optionsHandlerRoot(args) {
  yield all([fork(genericOptionsWatcher, args.apiRoot)])
}
```
will be attempting to make a plugin soon
