### ISSUE TITLE
[Question] real world example of using redux-resources with redux saga

### ISSUE THREAD

**Issue by meneman** [jamesplease/redux-resource#424]
Are the more examples how i can integrade redux-resources with redux-saga?

**Comment by djstein** [comment]
@meneman gotchu https://github.com/truebuildio/truebuild-frontend
this is a VERY abstracted project. combined with sagas that are bundle split, sagas + redux-resource variables/functions/etc all being generated

give it a few refreshes for form fields to populate as its all running on lambda https://www.truebuild.io

**Comment by jamesplease** [comment]
Thanks for sharing that link @djstein . I'm going to close this out for now, but if anyone else has additional links to add please do!
