### ISSUE TITLE
[Question] How can I remove an id in lists

### ISSUE THREAD

**Issue by tomzaku** [jamesplease/redux-resource#445]
i have a favourite list
```
{
lists: {
favorites: ["1","2"]
}
}
```
Now I would like to remove "1" out of my favourite list without delete the object "1" in resourses  object. How can I handle this case

**Comment by tomzaku** [comment]
First, I tried to use this one
```
 const favoritesList = getState().gallery.lists.favorites as string[];

    dispatch(
      removeFavoriteActionCreators.succeeded({
        resources: favoritesList.filter(favoritesId => id !== favoritesId),
        mergeListIds: false,
        disableUpdatePagination: true
      })
    );
  };
```
Do you have any better solution?

**Comment by jamesplease** [comment]
Hi @tomzaku ! There is an action type `UPDATE_RESOURCES` which can be used to update _just_ a list, without affecting the actual resource.

Using it may look like the following:

```js
function removeFromFavorites(favoritesId) {
  const favoritesList = getState().gallery.lists.favorites;
  const filteredList = favoritesList.filter(id => is !== favoritesId);

  dispatch({
    type: ‘UPDATE_RESOURCES’,
    lists: {
      gallery: {
        favorites: filteredList
      }
    }
  });
}
```

You can read more about this action type, and a related action type, `DELETE_RESOURCES`, here:

https://redux-resource.js.org/resources/modifying-resources
